defaults: &defaults
  host: ds053778.mongolab.com
  port: 53778

development:
  <<: *defaults
  database: stalking
  username: nicolas
  password: epsi

test:
  <<: *defaults
  database: stalking

# set these environment variables on your prod server
production:
  <<: *defaults
  database: stalking
  username: nicolas
  password: epsi