defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: db_development
  username: user
  password: password

test:
  <<: *defaults
  database: db_test

# set these environment variables on your prod server
production:
  <<: *defaults
  database:
  username:
  password: