defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: stalking
  username: dbuser
  password: password

test:
  <<: *defaults
  database: stalking

# set these environment variables on your prod server
production:
  <<: *defaults
  database: stalking
  username: dbuser
  password: dbpassword